apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
  labels:
    app: form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-service
  template:
    metadata:
      labels:
        app: form-service
    spec:
      serviceAccountName: circleguard-sa
      containers:
        - name: form-service
          image: circleguard/form-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/circleguard_form
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 5
