package com.circleguard.promotion.service;

import com.circleguard.promotion.model.graph.CircleNode;
import com.circleguard.promotion.repository.graph.CircleNodeRepository;
import com.circleguard.promotion.repository.graph.UserNodeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

class AutoCircleServiceTest {

    private UserNodeRepository userRepo;
    private CircleNodeRepository circleRepo;
    private CircleService circleService;
    private AutoCircleService service;

    @BeforeEach
    void setUp() {
        userRepo = mock(UserNodeRepository.class);
        circleRepo = mock(CircleNodeRepository.class);
        circleService = mock(CircleService.class);
        service = new AutoCircleService(userRepo, circleRepo, circleService);
    }

    @Test
    void evaluateEncounter_sameUser_isNoop() {
        service.evaluateEncounter("anon-1", "anon-1");
        verifyNoInteractions(userRepo);
        verifyNoInteractions(circleRepo);
    }

    @Test
    void evaluateEncounter_nullArgs_isNoop() {
        service.evaluateEncounter(null, "anon-1");
        service.evaluateEncounter("anon-1", null);
        verifyNoInteractions(userRepo);
    }

    @Test
    void evaluateEncounter_belowThreshold_doesNotCreateCircle() {
        // Threshold is 3600 seconds; 1000 is well below
        when(userRepo.getCumulativeEncounterDuration("anon-1", "anon-2")).thenReturn(1000L);

        service.evaluateEncounter("anon-1", "anon-2");

        verify(circleRepo, never()).save(any());
        verifyNoInteractions(circleService);
    }

    @Test
    void evaluateEncounter_aboveThresholdAndNoExistingAutoCircle_createsAndJoinsBoth() {
        when(userRepo.getCumulativeEncounterDuration("anon-1", "anon-2")).thenReturn(5400L);
        when(circleRepo.findCommonCircles("anon-1", "anon-2")).thenReturn(List.of());
        when(circleRepo.save(any())).thenAnswer(inv -> inv.getArgument(0));

        service.evaluateEncounter("anon-1", "anon-2");

        verify(circleRepo).save(any(CircleNode.class));
        // Both users joined into the new auto-circle
        verify(circleService).joinCircle(eq("anon-1"), anyString());
        verify(circleService).joinCircle(eq("anon-2"), anyString());
    }

    @Test
    void evaluateEncounter_aboveThresholdButAutoCircleExists_doesNothing() {
        when(userRepo.getCumulativeEncounterDuration("anon-1", "anon-2")).thenReturn(5400L);
        CircleNode existing = CircleNode.builder().isAutoGenerated(true).build();
        when(circleRepo.findCommonCircles("anon-1", "anon-2")).thenReturn(List.of(existing));

        service.evaluateEncounter("anon-1", "anon-2");

        verify(circleRepo, never()).save(any());
        verifyNoInteractions(circleService);
    }
}
